### ISSUE TITLE
Binary format

### ISSUE THREAD

**Issue by Ayms** [Voxer/sse4_crc32#26]
Please see https://github.com/ashi009/node-fast-crc32c/issues/2, the same problem occurs with sse4_crc32

**Comment by anandsuresh** [comment]
@Ayms I modified your code to be able to run it from the command line by adding the following line to the bottom of the index.js file:
```
generate_id(process.argv[2], process.argv[3]);
```

Then I run the following:
```
$ node index.js 124.31.75.21 1
5fbfbdb2
5fbfbcc51def47d63cc5df0378d35b60f616de01
```

Can you confirm that the output is correct?

**Comment by Ayms** [comment]
Yes, it is the problem occurs when the first byte to process is outside of the normal ascii range, so for generate_id('21.75.31.124',86) for example (21 becomes 0xc1 to process)

See https://github.com/ashi009/node-fast-crc32c/issues/2, apparently it's not an issue for @ashi009

I don't know what is specified for crc32c regarding representations that can have more than one byte.

But since other implementations behave differently, then maybe it's useful to add an option.

**Comment by anandsuresh** [comment]
The CRC calculation functions in this module expect a Buffer or a String. If you don't pass in a buffer, the input is treated as a UTF-8 encoded string.

I'd recommend passing in a binary-encoded buffer. That should fix the problem you are facing.

**Comment by Ayms** [comment]
Yes, that's not a problem for me, it's fixed, but you might consider an option or at least document it a bit better for others, it's not easy to get for people not used to CRC32C calculation, because you pass a "string" which in fact is interpreted as the hex representation of the "string", not knowing exactly how this is done, while probably most of c++ libs just handle it byte by byte, ie non utf8.

**Comment by anandsuresh** [comment]
Thanks for the feedback @Ayms. Will update the docs to make the encoding issue clearer.

**Comment by Ayms** [comment]
Thanks, I have tried to explain it too on bittorrent-nodeid repo
