### ISSUE TITLE
Cannot build on windows7 - "Linkage specification must be global"

### ISSUE THREAD

**Issue by MKHenson** [Voxer/sse4_crc32#33]
Hi @anandsuresh 

I have been struggling to get sse4_crc32 to install on my Windows 7 machine. I have node-gyp installed and its working as it is able to compile both the hello world examples as well as many of the other node_modules. However I cannot seem to get it to work for this project. I came here via gcloud and am at a bit of a loss on what to do <:/

My only thought is that there might be something in the 2010 compiler that is not compatible with the code. 

```
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\setjmp.h(40): error C2598: linkage specification must be at global scope [X:\projects\webinate-users\server\node_modules\sse4_crc32\build\sse4_crc32.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\setjmp.h(204): f
atal error C1903: unable to recover from previous error(s); stopping compilatio
n [X:\projects\webinate-users\server\node_modules\sse4_crc32\build\sse4_crc32.v
cxproj]
```

**Comment by MKHenson** [comment]
Was able to resolve this. I had to install VS2012 (2010 does not look like its supported) and use the command

    npm install --msvs_version=2012

If anyone else gets here - make sure you do it through windows cmd, as it didn't work when I used the SDK console window.

**Comment by anandsuresh** [comment]
Thanks for the resolution update @MKHenson.
