### ISSUE TITLE
Latest version leaks memory

### ISSUE THREAD

**Issue by Raynos** [Voxer/sse4_crc32#36]
We are seeing around 200mb/hr being leaked due to nan@2.0.0.

I recommend you downgrade nan.

We re-deployed with sse4_crc32@3.2.0 to avoid the leak.

**Comment by anandsuresh** [comment]
@Raynos Thanks for the update. Sounds like an issue that @rvagg could comment on.

In the mean time, I'm  reverting the changes in the update and pushing out a new version with the old nan. Then re-releasing a new major version with nan@v2

**Comment by anandsuresh** [comment]
Fixed in release v3.4.0

**Comment by kkoopa** [comment]
Fixed since NAN 2.0.5.
