### ISSUE TITLE
fallback

### ISSUE THREAD

**Issue by jonathanong** [Voxer/sse4_crc32#5]
since not all platforms are supported, for example ARM most likely, is there a way to fallback to the regular JS version? it doesn't have to be part of this module - just some documentation would be nice. ex, `optionalDependencies` and try/catch the `require("sse4_crc32")`.

also, the docs should read something like "Beginning with Nehalem, Intel processors...". currently, it sounds like only those processors support them even though they're like 6 years old.

also, you should put the benchmarks on the readme. here's mine:

```bash
100000 calls to calculate CRC on a 1024 byte buffer...
	SSE4.2 based CRC32: 31ms.
	Pure JS based CRC32 (table-based): 701ms.
	Pure JS based CRC32 (direct): 4147ms.

100000 calls to calculate CRC on random length buffers upto 4096 bytes long...
	Avg. buffer length: 2051 bytes
	SSE4.2 based CRC32: 57ms.
	Pure JS based CRC32 (table-based): 1992ms.
	Pure JS based CRC32 (direct): 8947ms.
```

**Comment by anandsuresh** [comment]
Finally got to the software fallback implementation @mranney. Turns out that h/w acceleration only gives you a speed up of 2x compared to the table-based lookup implementation in C. Both C/C++ versions of the function are still 1-2 orders of magnitude faster than pure JS.
