### ISSUE TITLE
Broken on Ubuntu 15.04

### ISSUE THREAD

**Issue by Chrisdf** [Voxer/sse4_crc32#51]
The stack trace I get when running 'npm install' is the following: 
> sse4_crc32@4.1.1 install /home/chrisfrantz/Dev/xenforma_server/node_modules/sse4_crc32
> node-gyp rebuild

make: Entering directory '/home/chrisfrantz/Dev/xenforma_server/node_modules/sse4_crc32/build'
  CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
make: g++: Command not found
crc32c_sse42.target.mk:89: recipe for target 'Release/obj.target/crc32c_sse42/src/crc32c_sse42.o' failed
make: *** [Release/obj.target/crc32c_sse42/src/crc32c_sse42.o] Error 127
make: Leaving directory '/home/chrisfrantz/Dev/xenforma_server/node_modules/sse4_crc32/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-47-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chrisfrantz/Dev/xenforma_server/node_modules/sse4_crc32
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPEERINVALID eslint-config-google@0.3.0 requires a peer of eslint@>=1.8.0 but none was installed.
npm WARN EPEERINVALID eslint-config-xo@0.7.1 requires a peer of eslint@>=1.7.3 but none was installed.
npm WARN EPEERINVALID mongodb-core@1.2.32 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 3.19.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! sse4_crc32@4.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sse4_crc32@4.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sse4_crc32 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sse4_crc32
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chrisfrantz/Dev/xenforma_server/npm-debug.log

**Comment by addaleax** [comment]
You need a compiler for building native modules. Doing a `sudo apt-get install build-essential` should install everything necessary so that `npm install` works.

**Comment by anandsuresh** [comment]
@Chrisdf Seems like you don't have the prerequisites (g++, in this case), as @addaleax pointed out.

I'm gonna close this issue for now. Feel free to re-open it if the `npm install` fails after installing gcc.
