### ISSUE TITLE
Help finding solution to mips compilation failure

### ISSUE THREAD

**Issue by rwaldron** [Voxer/sse4_crc32#52]
https://github.com/tessel/t2-cli/issues/645#issuecomment-207675894

Is there anyway to work around this? Even if it's a JS only "fallback"? It's been a long day, so this might not even make sense

**Comment by anandsuresh** [comment]
@rwaldron Interesting problem. Having never worked on the MIPS architecture, I'm a bit intrigued as to how that might work. I cannot guarantee a working solution, but I can spend some time this weekend to see if I can get it to work.

In the mean time, are there any MIPS resources (QEMU VMs, documentation) that you can point me to that might help me target the specifics of your platform?

**Comment by rwaldron** [comment]
> I can spend some time this weekend to see if I can get it to work.

That's excellent and I really appreciate that you're willing to take the time to look at this! I'll try to be as helpful as possible :)

**Comment by anandsuresh** [comment]
@rwaldron Did you get a chance to checkout pull-request #53? Does that solve your compilation issues?
