### ISSUE TITLE
Compatibility with nodejs 6

### ISSUE THREAD

**Issue by vitali-ausianik** [Voxer/sse4_crc32#59]
Looks like it is not compatible with nodejs version 6 - "node-gyp rebuild" fails on it

**Comment by addaleax** [comment]
It works for me. Can’t speak for the maintainer here but I’d say it might be helpful if you included your OS version here and maybe the output and/or the npm-debug.log…?

**Comment by anandsuresh** [comment]
Just tried running it with node v6.1.0 and it works just fine.

As @addaleax said.... got any logs?

**Comment by vitali-ausianik** [comment]
Sorry guys, looks like it is related to snappystream package that uses old version (^4.1.1) sse4_crc32

**Comment by vitali-ausianik** [comment]
i mean https://github.com/dudleycarr/snappystream/blob/master/package.json#L32

**Comment by anandsuresh** [comment]
Yup. That would do it!. Closing this now. Feel free to re-open if the problem persists.
