### ISSUE TITLE
Install fails on node-gyp rebuild

### ISSUE THREAD

**Issue by ronenm** [Voxer/sse4_crc32#61]
Hi,

I'm getting the following errors when trying to install the package.

Versions:
npm 3.9.3
node v6.2.1
node-gyp.js - V3.3.1
gcc 5.4.0 (installed specifically for the sse4_crc32 because I saw the bug may relate to gcc version)
libtoole - /usr/bin/libtool

Thanks

[log.txt](https://github.com/Voxer/sse4_crc32/files/299284/log.txt)

**Comment by addaleax** [comment]
@ronenm Are you sure node-gyp picks up on the fact that it should use your gcc 5.4.0 installation? `This version of node/NAN/v8 requires a C++11 compiler` sounds a lot like it does not (gcc 5.4.0 definitely supports compiling Node.js addons)

**Comment by ronenm** [comment]
@addaleax you are right. I installed gcc on /usr/local/bin while node-gyp probably was originally compiled and used /usr/bin/gcc (which was 4.4.7). 

To solve this I linked /usr/local/bin/gcc (and g++) to /usr/bin and re-installed npm and node-gyp (just to be sure).

Now everything's working fine. Thanks allot  :+1:
